$kind: http-example
request:
  url: "{{baseUrl}}/api/v1/eventattributevalue/?search=string"
  method: GET
  headers:
    Accept: application/json
  queryParams:
    - key: search
      value: string
      description: A search term.
response:
  statusCode: 200
  statusText: OK
  headers:
    Date: Thu, 23 Jul 2026 02:02:29 GMT
    Server: WSGIServer/0.2 CPython/3.12.13
    Content-Type: application/json
    Vary: Accept
    Allow: GET, POST, HEAD, OPTIONS
    X-Frame-Options: DENY
    Content-Length: "356"
    X-Content-Type-Options: nosniff
    Referrer-Policy: same-origin
    Cross-Origin-Opener-Policy: same-origin
  body:
    type: text
    content: |-
      [
          {
              "id": 4,
              "event": 7,
              "attribute": 6,
              "value_text": "Ahmad Eslami",
              "value_int": null,
              "value_bool": null,
              "created_at": "2026-07-23T01:55:29.999345Z",
              "updated_at": "2026-07-23T01:55:29.999392Z"
          },
          {
              "id": 5,
              "event": 7,
              "attribute": 8,
              "value_text": null,
              "value_int": null,
              "value_bool": false,
              "created_at": "2026-07-23T02:00:29.046822Z",
              "updated_at": "2026-07-23T02:00:29.046898Z"
          }
      ]
order: 2000
