# Generated by Django 6.0.3 on 2026-06-22 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان رویداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات رویداد')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('CLOSED', 'بسته شده'), ('FINISHED', 'پایان یافته')], default='DRAFT', max_length=15, verbose_name='وضعیت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='برگزارکننده')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
