# Generated by Django 6.0.3 on 2026-06-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مرحله')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات مرحله')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع مرحله')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان مرحله')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='event.event', verbose_name='رویداد مربوطه')),
            ],
            options={
                'verbose_name': 'مرحله رویداد',
                'verbose_name_plural': 'مراحل رویداد',
                'ordering': ['start_time'],
            },
        ),
    ]
