# Generated by Django 6.0.3 on 2026-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'رویداد', 'verbose_name_plural': 'رویداد ها'},
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PUBLISHED', 'منتشر شده'), ('ONGOING', 'در حال برگزاری'), ('CLOSED', 'بسته شده'), ('FINISHED', 'پایان یافته'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=15, verbose_name='وضعیت'),
        ),
    ]
