# Generated by Django 6.0.3 on 2026-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_options_alter_event_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstage',
            options={'ordering': ['order'], 'verbose_name': 'مرحله رویداد', 'verbose_name_plural': 'مراحل رویداد'},
        ),
        migrations.AddField(
            model_name='eventstage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
            preserve_default=False,
        ),
    ]
