# Generated by Django 6.0.3 on 2026-06-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_eventstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ویژگی')),
                ('data_type', models.CharField(choices=[('TEXT', 'متنی'), ('INTEGER', 'عددی'), ('BOOLEAN', 'بولین (بله/خیر)')], max_length=15, verbose_name='نوع داده\u200cای')),
            ],
            options={
                'verbose_name': 'ویژگی داینامیک',
                'verbose_name_plural': 'ویژگی\u200cهای داینامیک',
            },
        ),
        migrations.CreateModel(
            name='EventAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='مقدار متنی')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='مقدار عددی')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='مقدار بولین')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_values', to='attribute.attribute', verbose_name='ویژگی')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='event.event', verbose_name='رویداد')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی رویداد',
                'verbose_name_plural': 'مقادیر ویژگی\u200cهای رویداد',
                'unique_together': {('event', 'attribute')},
            },
        ),
    ]
