# Generated by Django 6.0.3 on 2026-06-25 07:35

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slugs(apps, schema_editor):
    Attribute = apps.get_model('attribute', 'Attribute')
    existing_slugs = set()

    for attribute in Attribute.objects.all().order_by('pk'):
        base_slug = slugify(attribute.name, allow_unicode=True) or f'attribute-{attribute.pk}'
        base_slug = base_slug[:240]

        slug = base_slug
        counter = 1
        while slug in existing_slugs or Attribute.objects.filter(slug=slug).exclude(pk=attribute.pk).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1

        existing_slugs.add(slug)
        attribute.slug = slug
        attribute.save(update_fields=['slug'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.RunPython(generate_unique_slugs, reverse_noop),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
    ]