# Generated by Django 6.0.3 on 2026-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=20.0, max_length=255, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
