# Generated by Django 6.0.3 on 2026-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.CharField(choices=[('ORGANIZER', 'Organizer'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=15, verbose_name=' نقش')),
                ('phone', models.CharField(help_text='شماره باید منحصر به فرد باشد.', max_length=20, unique=True, verbose_name='شماره')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, help_text='مشخص میکند آیا کاربر فعال است یا نه')),
                ('is_staff', models.BooleanField(default=False, help_text='مشخص میکند آیا این کاربر میتواند وارد پنل ادمین شود یا نه')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
