# Generated by Django 6.0.3 on 2026-06-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
    ]
