# Generated by Django 6.0.3 on 2026-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('PARTICIPANT', 'Participant'), ('STAFF', 'staff')], default='PARTICIPANT', max_length=15, verbose_name=' نقش'),
        ),
    ]
